spring.application.name=biblioteca

# Configuração da Conexão com o Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/biblioteca_api
spring.datasource.username=root
spring.datasource.password=

# Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

#  Formato padrão para datas no projeto inteiro
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Chave secreta para assinar o JWT
security.jwt.secret-key=a367a360f1172815d869baacbbd90dab0b247b4483554a352041b73e30b3cdc5
# Tempo de expiração em milissegundos (1h)
security.jwt.expiration-time=3600000


#Código admin
biblioteca.admin.codigo-secreto=BG25ADM

# =========================================
# CONFIGURAÇÃO DE ENVIO DE E-MAIL (GMAIL)
# =========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contato.biblioteca.api@gmail.com
spring.mail.password=lqfivmctepbcrjvu

# Propriedades adicionais do JavaMail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true